config/routes.rb
DemoApp::Application.routes.draw do

  get "events/new"
  get "events/create"
  get "events/show"
  get "events/index"
  get "events/destroy"
  get "events/calendar"

  get "orders/new"
  get "orders/create"
  get "orders/destroy"
  get "orders/show"

  get "place/create"
  get "place/index"
  get "place/destroy"
  get "place/manage"

  get "static_pages/home"
  get "static_pages/help"
	get "static_pages/about"
	get "static_pages/contact"
	get "static_pages/hall"

	match '/signup',  to: 'users#new'
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

	match '/help', to: 'static_pages#help'
	match '/about', to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'
  match '/hall', to: 'static_pages#hall'
  
  match '/add_place', to: 'places#new'
  match '/manage_places', to: 'places#manage'

  resources :microposts, only: [:create, :destroy]
  resources :users
	resources :sessions, only: [:new, :create, :destroy]
	
	resources :events do
	   resources :places 
	end
	
	resources :places do
     resources :orders
  end
	

  root :to => 'static_pages#home'

end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :number, :price, :event_id
  
  validates :number, presence: true
  #validates :price,  presence: true
  
  has_one :order
  belongs_to :event
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  
  def new
    @place = Place.new
  end
  
  def create
    @place = Place.new(params[:place])
    if @place.save
      flash[:success] = "Place Added!"
      redirect_to places_path
    end
  end

  def index
    #@order = Order.all
    @place = Place.all
  end

  def destroy
    Place.find(params[:id]).destroy
    redirect_to places_path
  end
  
  def manage
    @place = Place.all
  end
  
  def show
    @event = Event.find(params[:event_id])
    @place = @event.places.find(params[:id])
    @order = Order.new(params[:order])
  end
  
end

app/helpers/place_helper.rb
module PlaceHelper
  
  def current_place
    @place ||= Place.find_by_id(params[:id])
  end
  
  
end

app/views/places/destroy.html.erb
<h1>Place#destroy</h1>
<p>Find me in app/views/place/destroy.html.erb</p>

app/views/places/index.html.erb
<div class="row">
	<div class="span12 offset3">
			<div class="places">
		<% @place.each do |place| %>
			
		<% if place.status == 1 %>
			<div class="busy-place">
		<% else %>
			<div class="free-place">
		<% end %>
		<%= link_to place.number, place %>			</span>
			</div>
		<% if (place.number % 10) == 0 %>
		<br><br>
		<%end%>
		
		 <% end %>
		</div>
	</div>
</div>

<%= link_to "Manage places" , manage_places_path %>

app/views/places/manage.html.erb
<div class="row">
	<div class="span12 offset3">
		<% @place.each do |place| %>
		<li>
		<%= place.number %>
		<%= link_to "delete", place, method: :delete, confirm: "sure?"%>
		</li>
		<% end %>
		 
	</div>
</div>

<%= link_to "Add another place" , add_place_path %>

app/views/places/new.html.erb
<h1>Add place</h1>
	<div class="row">
		<div class="span6 offset3">
			<%= form_for(@place) do |place| %>

				<%= render 'shared/error_messages', object: place.object %>
		
				<%= place.label :number %>
				<%= place.text_field :number %>
				
				<%= place.label :price %>
				<%= place.text_field :price %>
			

				<%= place.submit "add place", class: "btn btn-large btn-primary" %>
				<% end %>
		</div>
	</div>

app/views/places/show.html.erb
<div class="row">
	<div class="span5">
		Place number<span class="label label-success"> <%= @place.number%> </span> <br>
		place Price<span class="label label-success"> <%= @place.price %> $</span><br>
		event name <span class="label label-success"><%= @event.name %> </span><br>
		
	<%= link_to "Make Order", new_place_order_path(@place) %>
	
	</div>

	
</div>