config/routes.rb
DemoApp::Application.routes.draw do

  get "events/new"
  get "events/create"
  get "events/show"
  get "events/index"
  get "events/destroy"
  get "events/calendar"

  get "orders/new"
  get "orders/create"
  get "orders/destroy"
  get "orders/show"

  get "place/create"
  get "place/index"
  get "place/destroy"
  get "place/manage"

  get "static_pages/home"
  get "static_pages/help"
	get "static_pages/about"
	get "static_pages/contact"
	get "static_pages/hall"

	match '/signup',  to: 'users#new'
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

	match '/help', to: 'static_pages#help'
	match '/about', to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'
  match '/hall', to: 'static_pages#hall'
  
  match '/add_place', to: 'places#new'
  match '/manage_places', to: 'places#manage'

  resources :microposts, only: [:create, :destroy]
  resources :users
	resources :sessions, only: [:new, :create, :destroy]
	
	resources :events do
	   resources :places 
	end
	
	resources :places do
     resources :orders
  end
	

  root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<a href="http://railstutorial.org/">Rails Tutorial</a>
by Michael Hartl
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<%= link_to "sample app", '#', id: "logo" %>
<nav>
<ul class="nav pull-right">
<li><%= link_to "Home",  root_path %></li>
<li><%= link_to "Help",  help_path %></li>
<li><%= link_to "Event List",  events_path %></li>

	<% if signed_in? %>
	
	<li><%= link_to "Create Event", new_event_path %></li>
	<li><%= link_to "users", users_path %></li>
	<li><%= link_to "Sign out", signout_path, method: "delete" %> </li>
	<li><%= link_to "My Profile", current_user %></li>
	<li><%= link_to "Settings", edit_user_path(current_user) %></li>

	
	<% else %>
		<li><%= link_to "Sign_in", signin_path %></li>

	<% end %>
</ul>
	

</nav>
</div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<%= stylesheet_link_tag "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
	<br>
	<% flash.each do |name, msg| %>
 		 <% if msg.is_a?(String) %>
   		 <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
     		 <a class="close" data-dismiss="alert">&#215;</a>
     		 <%= content_tag :div, msg, :id => "flash_#{name}" %>
   		 </div>
  		<% end %>
	<% end %>

	<%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>